name: Build LaTeX cover letter
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        working-directory: ./src
        uses: xu-cheng/latex-action@v3
        with:
          root_file: coverletter.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: cover-letter.pdf