name: Build LaTeX cover letter
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: ./src
          root_file: cover-letter.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: reed-markham-cover-letter
          working_directory: src
          path: cover-letter.pdf