name: Build DE LaTeX resume
on:
  push:
    paths:
      - 'src/de-resume.tex'
      - 'src/*.cls'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Put current date into a variable
        run: echo "DT=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: de-resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: reed-markham-de-resume-${{env.DT}}
          path: src/de-resume.pdf