name: Build LaTeX resume
on:
  push:
    paths:
      - 'src/ds-resume.tex'
      - 'src/*.cls'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: ds-resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: reed-markham-ds-resume
          path: src/ds-resume.pdf