name: Resume CI/CD
on:
  push:
    paths:
      - 'src/resume.tex'
      - 'src/*.cls'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: src
          root_file: resume.tex

      - name: Check PDF page count and fail if >1
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils
          PAGE_COUNT=$(pdfinfo src/resume.pdf | awk '/^Pages:/ {print $2}')
          if [ "$PAGE_COUNT" -gt 1 ]; then
            CHAR_COUNT=$(wc -m < src/resume.tex)
            echo "PDF is $PAGE_COUNT pages. Please shorten your resume."
            echo "Your .tex file has $CHAR_COUNT characters."
            echo "Estimate: Remove enough content to fit on 1 page."
            exit 1
          fi
      
      - name: Format date and rename file
        run: |
          today=$(date +'%m%d')
          mv src/resume.pdf "ReedMarkhamResume${today}.pdf"
          echo "RENAMED_FILE=ReedMarkhamResume${today}.pdf" >> $GITHUB_ENV

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: reed-markham-resume
          path: ${{ env.RENAMED_FILE }}